server.port: 9003

kafka:
  servers: 78.70.35.171:9001,78.70.35.171:9002,78.70.35.171:9003
  inTopic: orders-jobi
  applicationId: orders-streaming-jobi
  packTopic: packing-jobi
  backorderTopic: backorders-jobi
  groupId: order-processor-jobi
